<a href="https://colab.research.google.com/github/nimadeerap-ui/Ni-Made-Era-Purnama-Dewi/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Membuat array Data Nilai

In [1]:
import numpy as np

arr = np.array( [70, 65, 85, 90, 66] )


Tampilkan data array

In [2]:
print("data array: ")
print(arr)

data array: 
[70 65 85 90 66]


Fungsi statistik pada numpy

In [11]:
nRendah = np.min(arr)
print("Nilai Terendah: ")
print(nRendah)

nTinggi = np.max(arr)
print("Nilai Tertingi: ")
print(nTinggi)

nRata = np.mean(arr)
print("Nilai rata rata: ")
print(nRata)

Nilai Terendah: 
65
Nilai Tertingi: 
90
Nilai rata rata: 
75.2


Array dua dimensi

In [12]:
matrik = np.array( [ [4,3,7], [2,1,8] ] )

Tampilkan array

In [15]:
print(matrik)

[[4 3 7]
 [2 1 8]]


In [16]:
print(matrik[1,2])

8


In [24]:
matrik2 = np.array([
    [3, 5, 7, 1, 8],
    [6, 3, 1, 8, 3],
    [6, 5, 2, 7, 9],
    [4, 2, 9, 4, 7]
])

In [25]:
print(matrik2[1,2])

1


In [28]:
matrik3 = np.array([
    [
        [13,51,11],[9,4,32],[10,12,43]
    ],

     [
         [22,23,24],[41,42,44],[31,33,34]
     ],
    [
        [52,55,58],[63,62,69],[77,70,79]
    ]

])

In [29]:
print(matrik3[1,1,1])

42
